# Generated by Django 5.0.14 on 2026-04-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
